export GOPATH="$HOME/.go:$GOPATH"
export OSA_LIBRARY_PATH="$HOME/dotfiles/script-libraries:$OSA_LIBRARY_PATH"

# Add paths to path variable with increasing priority
# Global executables
export PATH="$HOME/bin:$PATH"

# User executables
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

# PHP
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"

# Postgres
export PATH="/Applications/Postgres.app/Contents/Versions/9.4/bin:$PATH"

# Go executables
export PATH="$GOPATH/bin:$PATH"

# Ruby Gems
export PATH="$(brew --prefix ruby)/bin:$PATH"

# Npm executables
export PATH="/usr/local/share/npm/bin:$PATH"

# Custom user scripts
export PATH="$HOME/dotfiles/bin:$PATH"


export JAVA_HOME=$(/usr/libexec/java_home)

# Colors for Man Pages displayed with "Less"
export LESS_TERMCAP_mb=$'\E[01;31m'         # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'    # begin bold
export LESS_TERMCAP_me=$'\E[0m'             # end mode
export LESS_TERMCAP_se=$'\E[0m'             # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'      # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'             # end underline
export LESS_TERMCAP_us=$'\E[01;38;5;209m'   # begin underline

# 256 colors
export TERM=xterm-256color

# Include aliases
if [ -f ~/.bash_aliases ]
then
	. ~/.bash_aliases
fi

# Z
. $(brew --prefix)/etc/profile.d/z.sh

# NVM
export NVM_DIR="/Users/adrian/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Grep
export GREP_OPTIONS='--color=always'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Default editor
export EDITOR=atom

# added by travis gem
[ -f /Users/adrian/.travis/travis.sh ] && source /Users/adrian/.travis/travis.sh
