alias mv="mv -i"

alias ..="cd .."			#go to parent dir
alias ...="cd ../.."		#go to grandparent dir
alias l.='ls -dG .*'		#list hidden files
alias ll='ls -alhG'		#extra info compared to "l"
alias lld='ls -lUdG */'	#list directories

alias branch='git branch'
alias pull='git pull'
alias push='git push'
alias commit='git commit'

alias ij='open -a "IntelliJ IDEA 13"'
alias chrome='open -a "Google Chrome"'
alias handbrake='open -a "HandBrake"'

alias dropbox='~/Sites/Dropbox-Uploader/dropbox_uploader.sh'
