source ~/.bash_login
source ~/.bashrc
source ~/.profile

export PATH="$HOME/.cargo/bin:$PATH"

source /Users/adrian/Library/Preferences/org.dystroy.broot/launcher/bash/br

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/adrian/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/adrian/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/adrian/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/adrian/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

